// Lobster GUI State Machine
//
#include "types.h"
#include "state_mach.h"
#include "lob.h"

//#define LOBNUMBUT 48 //47

// C18 to XC8 Compiler Changes start
//const rom char *state_name[ST_MAX] = {
//const char *state_name[ST_MAX] = {		// not used
//  "SLEEP              ",  "IDLE               ",  "MANUAL MAIN        ",
//  "PRESET MAIN        ",  "PERS PROG MAIN     ",  "PLAY               ",
//  "ABORT              ",  "TEST SHOT          " 
//};
// C18 to XC8 Compiler Changes end

//const rom uchar xmsk[LOBNUMBUT] = {
//	0,0,1,1,0,1,1,0,	//0-7
//	0,0,0,0,0,0,0,0,	//8-f
//	0,0,0,0,0,0,0,0,	//10-17
//	0,0,0,0,0,0,0,0,	//18-1f
//	0,0,0,0,0,0,0,0,	//20-27
//	0,0,0,0,0,0,1,1,	//21-2f
//};
//
#define XTBL_SIZE ((LOBNUMBUT) * (ST_MAX)) // can't use - compiler won't handle right

// Lobster GUI State Translation Table
//

// C18 to XC8 Compiler Changes
//const rom uchar xtbl[384] = {
const uchar xtbl[384] = {
// C18 to XC8 Compiler Changes

//       		Sleep    Idle     ManMain   PreMain   PrgMain   Play	 Abort		Test
/*NoChg	  0 */  ST_SLEEP,ST_IDLE, ST_MANMN, ST_PREMN, ST_PRGMN, ST_PLAY, ST_IDLE,	ST_TEST,
/*MenuDN  1 */  ST_SLEEP,ST_IDLE, ST_MANMN, ST_PREMN, ST_PRGMN, ST_PLAY, ST_ABORT,ST_TEST,
/*Preset  2 */  ST_SLEEP,ST_PREMN,ST_ABORT, ST_PREMN, ST_ABORT, ST_ABORT,ST_ABORT,ST_ABORT,
/*Play	  3 */  ST_SLEEP,ST_IDLE, ST_PLAY,	ST_PLAY,  ST_PLAY,	ST_ABORT,ST_PLAY,	ST_TEST,
/* + 	  4 */  ST_SLEEP,ST_IDLE, ST_MANMN, ST_PREMN, ST_PRGMN, ST_PLAY, ST_ABORT,ST_TEST,
/*Program 5 */  ST_SLEEP,ST_PRGMN,ST_ABORT, ST_ABORT, ST_PRGMN, ST_ABORT,ST_ABORT,ST_ABORT,
/*Manual  6 */  ST_SLEEP,ST_MANMN,ST_MANMN, ST_ABORT, ST_ABORT, ST_ABORT,ST_ABORT,ST_ABORT,
/*Locn06  7 */  ST_SLEEP,ST_IDLE, ST_MANMN, ST_PREMN, ST_PRGMN, ST_PLAY, ST_ABORT,ST_TEST,
/*Locn18  8 */  ST_SLEEP,ST_IDLE, ST_MANMN, ST_PREMN, ST_PRGMN, ST_PLAY, ST_ABORT,ST_TEST,
/*Locn12  9 */  ST_SLEEP,ST_IDLE ,ST_MANMN, ST_PREMN, ST_PRGMN, ST_PLAY, ST_ABORT,ST_TEST,
/*Locn24 10 */  ST_SLEEP,ST_IDLE ,ST_MANMN, ST_PREMN, ST_PRGMN, ST_PLAY, ST_ABORT,ST_TEST,
/*Locn30 11 */  ST_SLEEP,ST_IDLE ,ST_MANMN, ST_PREMN, ST_PRGMN, ST_PLAY, ST_ABORT,ST_TEST,
/*Locn36 12 */  ST_SLEEP,ST_IDLE ,ST_MANMN, ST_PREMN, ST_PRGMN, ST_PLAY, ST_ABORT,ST_TEST,
/*Locn05 13 */  ST_SLEEP,ST_IDLE ,ST_MANMN, ST_PREMN, ST_PRGMN, ST_PLAY, ST_ABORT,ST_TEST,
/*Locn17 14 */  ST_SLEEP,ST_IDLE ,ST_MANMN, ST_PREMN, ST_PRGMN, ST_PLAY, ST_ABORT,ST_TEST,
/*Locn11 15 */  ST_SLEEP,ST_IDLE ,ST_MANMN, ST_PREMN, ST_PRGMN, ST_PLAY, ST_ABORT,ST_TEST,
/*Locn23 16 */  ST_SLEEP,ST_IDLE ,ST_MANMN, ST_PREMN, ST_PRGMN, ST_PLAY, ST_ABORT,ST_TEST,
/*Locn29 17 */  ST_SLEEP,ST_IDLE ,ST_MANMN, ST_PREMN, ST_PRGMN, ST_PLAY, ST_ABORT,ST_TEST,
/*Locn35 18 */  ST_SLEEP,ST_IDLE ,ST_MANMN, ST_PREMN, ST_PRGMN, ST_PLAY, ST_ABORT,ST_TEST,
/*Locn04 19 */  ST_SLEEP,ST_IDLE ,ST_MANMN, ST_PREMN, ST_PRGMN, ST_PLAY, ST_ABORT,ST_TEST,
/*Locn16 20 */  ST_SLEEP,ST_IDLE ,ST_MANMN, ST_PREMN, ST_PRGMN, ST_PLAY, ST_ABORT,ST_TEST,
/*Locn10 21 */  ST_SLEEP,ST_IDLE ,ST_MANMN, ST_PREMN, ST_PRGMN, ST_PLAY, ST_ABORT,ST_TEST,
/*Locn22 22 */  ST_SLEEP,ST_IDLE ,ST_MANMN, ST_PREMN, ST_PRGMN, ST_PLAY, ST_ABORT,ST_TEST,
/*Locn28 23 */  ST_SLEEP,ST_IDLE ,ST_MANMN, ST_PREMN, ST_PRGMN, ST_PLAY, ST_ABORT,ST_TEST,
/*Locn34 24 */  ST_SLEEP,ST_IDLE ,ST_MANMN, ST_PREMN, ST_PRGMN, ST_PLAY, ST_ABORT,ST_TEST,
/*Locn03 25 */  ST_SLEEP,ST_IDLE ,ST_MANMN, ST_PREMN, ST_PRGMN, ST_PLAY, ST_ABORT,ST_TEST,
/*Locn15 26 */  ST_SLEEP,ST_IDLE ,ST_MANMN, ST_PREMN, ST_PRGMN, ST_PLAY, ST_ABORT,ST_TEST,
/*Locn09 27 */  ST_SLEEP,ST_IDLE ,ST_MANMN, ST_PREMN, ST_PRGMN, ST_PLAY, ST_ABORT,ST_TEST,
/*Locn21 28 */  ST_SLEEP,ST_IDLE ,ST_MANMN, ST_PREMN, ST_PRGMN, ST_PLAY, ST_ABORT,ST_TEST,
/*Locn27 29 */  ST_SLEEP,ST_IDLE ,ST_MANMN, ST_PREMN, ST_PRGMN, ST_PLAY, ST_ABORT,ST_TEST,
/*Locn33 30 */  ST_SLEEP,ST_IDLE ,ST_MANMN, ST_PREMN, ST_PRGMN, ST_PLAY, ST_ABORT,ST_TEST,
/*Locn02 31 */  ST_SLEEP,ST_IDLE ,ST_MANMN, ST_PREMN, ST_PRGMN, ST_PLAY, ST_ABORT,ST_TEST,
/*Locn14 32 */  ST_SLEEP,ST_IDLE ,ST_MANMN, ST_PREMN, ST_PRGMN, ST_PLAY, ST_ABORT,ST_TEST,
/*Locn08 33 */  ST_SLEEP,ST_IDLE ,ST_MANMN, ST_PREMN, ST_PRGMN, ST_PLAY, ST_ABORT,ST_TEST,
/*Locn20 34 */  ST_SLEEP,ST_IDLE ,ST_MANMN, ST_PREMN, ST_PRGMN, ST_PLAY, ST_ABORT,ST_TEST,
/*Locn26 35 */  ST_SLEEP,ST_IDLE ,ST_MANMN, ST_PREMN, ST_PRGMN, ST_PLAY, ST_ABORT,ST_TEST,
/*Locn32 36 */  ST_SLEEP,ST_IDLE ,ST_MANMN, ST_PREMN, ST_PRGMN, ST_PLAY, ST_ABORT,ST_TEST,
/*Locn01 37 */  ST_SLEEP,ST_IDLE ,ST_MANMN, ST_PREMN, ST_PRGMN, ST_PLAY, ST_ABORT,ST_TEST,
/*Locn13 38 */  ST_SLEEP,ST_IDLE ,ST_MANMN, ST_PREMN, ST_PRGMN, ST_PLAY, ST_ABORT,ST_TEST,
/*Locn07 39 */  ST_SLEEP,ST_IDLE ,ST_MANMN, ST_PREMN, ST_PRGMN, ST_PLAY, ST_ABORT,ST_TEST,
/*Locn19 40 */  ST_SLEEP,ST_IDLE ,ST_MANMN, ST_PREMN, ST_PRGMN, ST_PLAY, ST_ABORT,ST_TEST,
/*Locn25 41 */  ST_SLEEP,ST_IDLE ,ST_MANMN, ST_PREMN, ST_PRGMN, ST_PLAY, ST_ABORT,ST_TEST,
/*Locn31 42 */  ST_SLEEP,ST_IDLE ,ST_MANMN, ST_PREMN, ST_PRGMN, ST_PLAY, ST_ABORT,ST_TEST,
/* -		 43 */  ST_SLEEP,ST_IDLE, ST_MANMN, ST_PREMN, ST_PRGMN, ST_PLAY, ST_ABORT,ST_TEST,
/*			 44 */  ST_SLEEP,ST_IDLE ,ST_MANMN, ST_PREMN, ST_PRGMN, ST_PLAY, ST_ABORT,ST_TEST,
/*MenuUp 45 */  ST_SLEEP,ST_IDLE, ST_MANMN, ST_PREMN, ST_PRGMN, ST_PLAY, ST_ABORT,ST_TEST,
/*TEST   46 */  ST_SLEEP,ST_TEST, ST_TEST, 	ST_TEST,  ST_TEST,  ST_PLAY, ST_ABORT,ST_TEST,
/*Remote 47 */  ST_SLEEP,ST_IDLE ,ST_MANMN, ST_PREMN, ST_PRGMN, ST_PLAY, ST_ABORT,ST_TEST,
};

// ELO4CHG #2 (start)

// C18 to XC8 Compiler Changes
//const rom uchar xtbl_EL04[384] = {
const uchar xtbl_EL04[384] = {
// C18 to XC8 Compiler Changes

//       		Sleep    Idle     ManMain   PreMain   PrgMain   Play	 Abort		Test
/*NoChg	  0 */  ST_SLEEP,ST_IDLE, ST_MANMN, ST_PREMN, ST_PRGMN, ST_PLAY, ST_IDLE,	ST_TEST,
/*MenuDN  1 */  ST_SLEEP,ST_IDLE, ST_MANMN, ST_PREMN, ST_PRGMN, ST_PLAY, ST_ABORT,ST_TEST,
/*Preset  2 */  ST_SLEEP,ST_PREMN,ST_ABORT, ST_PREMN, ST_ABORT, ST_ABORT,ST_ABORT,ST_ABORT,
/*Play	  3 */  ST_SLEEP,ST_IDLE, ST_PLAY,	ST_PLAY,  ST_PLAY,	ST_ABORT,ST_PLAY,	ST_TEST,
/* + 	  4 */  ST_SLEEP,ST_IDLE, ST_MANMN, ST_PREMN, ST_PRGMN, ST_PLAY, ST_ABORT,ST_TEST,
/*Program 5 */  ST_SLEEP,ST_PRGMN,ST_ABORT, ST_ABORT, ST_PRGMN, ST_ABORT,ST_ABORT,ST_ABORT,
/*Manual  6 */  ST_SLEEP,ST_MANMN,ST_MANMN, ST_ABORT, ST_ABORT, ST_ABORT,ST_ABORT,ST_ABORT,
/*Preset  2 */  ST_SLEEP,ST_PREMN,ST_ABORT, ST_PREMN, ST_ABORT, ST_ABORT,ST_ABORT,ST_ABORT,
///*Locn06  7 */ST_SLEEP,ST_IDLE, ST_MANMN, ST_PREMN, ST_PRGMN, ST_PLAY, ST_ABORT,ST_TEST,
/*Preset  2 */  ST_SLEEP,ST_PREMN,ST_ABORT, ST_PREMN, ST_ABORT, ST_ABORT,ST_ABORT,ST_ABORT,
///*Locn18  8 */ST_SLEEP,ST_IDLE, ST_MANMN, ST_PREMN, ST_PRGMN, ST_PLAY, ST_ABORT,ST_TEST,
/*Preset  2 */  ST_SLEEP,ST_PREMN,ST_ABORT, ST_PREMN, ST_ABORT, ST_ABORT,ST_ABORT,ST_ABORT,
///*Locn12  9 */ST_SLEEP,ST_IDLE ,ST_MANMN, ST_PREMN, ST_PRGMN, ST_PLAY, ST_ABORT,ST_TEST,
/*Locn24 10 */  ST_SLEEP,ST_IDLE ,ST_MANMN, ST_PREMN, ST_PRGMN, ST_PLAY, ST_ABORT,ST_TEST,
/*Locn30 11 */  ST_SLEEP,ST_IDLE ,ST_MANMN, ST_PREMN, ST_PRGMN, ST_PLAY, ST_ABORT,ST_TEST,
/*Locn36 12 */  ST_SLEEP,ST_IDLE ,ST_MANMN, ST_PREMN, ST_PRGMN, ST_PLAY, ST_ABORT,ST_TEST,
/*Locn05 13 */  ST_SLEEP,ST_IDLE ,ST_MANMN, ST_PREMN, ST_PRGMN, ST_PLAY, ST_ABORT,ST_TEST,
/*Locn17 14 */  ST_SLEEP,ST_IDLE ,ST_MANMN, ST_PREMN, ST_PRGMN, ST_PLAY, ST_ABORT,ST_TEST,
/*Locn11 15 */  ST_SLEEP,ST_IDLE ,ST_MANMN, ST_PREMN, ST_PRGMN, ST_PLAY, ST_ABORT,ST_TEST,
/*Locn23 16 */  ST_SLEEP,ST_IDLE ,ST_MANMN, ST_PREMN, ST_PRGMN, ST_PLAY, ST_ABORT,ST_TEST,
/*Locn29 17 */  ST_SLEEP,ST_IDLE ,ST_MANMN, ST_PREMN, ST_PRGMN, ST_PLAY, ST_ABORT,ST_TEST,
/*Locn35 18 */  ST_SLEEP,ST_IDLE ,ST_MANMN, ST_PREMN, ST_PRGMN, ST_PLAY, ST_ABORT,ST_TEST,
/*Preset  2 */  ST_SLEEP,ST_PREMN,ST_ABORT, ST_PREMN, ST_ABORT, ST_ABORT,ST_ABORT,ST_ABORT,
///*Locn04 19 */ST_SLEEP,ST_IDLE ,ST_MANMN, ST_PREMN, ST_PRGMN, ST_PLAY, ST_ABORT,ST_TEST,
/*Preset  2 */  ST_SLEEP,ST_PREMN,ST_ABORT, ST_PREMN, ST_ABORT, ST_ABORT,ST_ABORT,ST_ABORT,
///*Locn16 20 */ST_SLEEP,ST_IDLE ,ST_MANMN, ST_PREMN, ST_PRGMN, ST_PLAY, ST_ABORT,ST_TEST,
/*Preset  2 */  ST_SLEEP,ST_PREMN,ST_ABORT, ST_PREMN, ST_ABORT, ST_ABORT,ST_ABORT,ST_ABORT,
///*Locn10 21 */ST_SLEEP,ST_IDLE ,ST_MANMN, ST_PREMN, ST_PRGMN, ST_PLAY, ST_ABORT,ST_TEST,
/*Locn22 22 */  ST_SLEEP,ST_IDLE ,ST_MANMN, ST_PREMN, ST_PRGMN, ST_PLAY, ST_ABORT,ST_TEST,
/*Locn28 23 */  ST_SLEEP,ST_IDLE ,ST_MANMN, ST_PREMN, ST_PRGMN, ST_PLAY, ST_ABORT,ST_TEST,
/*Locn34 24 */  ST_SLEEP,ST_IDLE ,ST_MANMN, ST_PREMN, ST_PRGMN, ST_PLAY, ST_ABORT,ST_TEST,
/*Locn03 25 */  ST_SLEEP,ST_IDLE ,ST_MANMN, ST_PREMN, ST_PRGMN, ST_PLAY, ST_ABORT,ST_TEST,
/*Locn15 26 */  ST_SLEEP,ST_IDLE ,ST_MANMN, ST_PREMN, ST_PRGMN, ST_PLAY, ST_ABORT,ST_TEST,
/*Locn09 27 */  ST_SLEEP,ST_IDLE ,ST_MANMN, ST_PREMN, ST_PRGMN, ST_PLAY, ST_ABORT,ST_TEST,
/*Locn21 28 */  ST_SLEEP,ST_IDLE ,ST_MANMN, ST_PREMN, ST_PRGMN, ST_PLAY, ST_ABORT,ST_TEST,
/*Locn27 29 */  ST_SLEEP,ST_IDLE ,ST_MANMN, ST_PREMN, ST_PRGMN, ST_PLAY, ST_ABORT,ST_TEST,
/*Locn33 30 */  ST_SLEEP,ST_IDLE ,ST_MANMN, ST_PREMN, ST_PRGMN, ST_PLAY, ST_ABORT,ST_TEST,
/*Preset  2 */  ST_SLEEP,ST_PREMN,ST_ABORT, ST_PREMN, ST_ABORT, ST_ABORT,ST_ABORT,ST_ABORT,
///*Locn02 31 */ST_SLEEP,ST_IDLE ,ST_MANMN, ST_PREMN, ST_PRGMN, ST_PLAY, ST_ABORT,ST_TEST,
/*Preset  2 */  ST_SLEEP,ST_PREMN,ST_ABORT, ST_PREMN, ST_ABORT, ST_ABORT,ST_ABORT,ST_ABORT,
//*Locn14 32 */ ST_SLEEP,ST_IDLE ,ST_MANMN, ST_PREMN, ST_PRGMN, ST_PLAY, ST_ABORT,ST_TEST,
/*Preset  2 */  ST_SLEEP,ST_PREMN,ST_ABORT, ST_PREMN, ST_ABORT, ST_ABORT,ST_ABORT,ST_ABORT,
///*Locn08 33 */ST_SLEEP,ST_IDLE ,ST_MANMN, ST_PREMN, ST_PRGMN, ST_PLAY, ST_ABORT,ST_TEST,
/*Locn20 34 */  ST_SLEEP,ST_IDLE ,ST_MANMN, ST_PREMN, ST_PRGMN, ST_PLAY, ST_ABORT,ST_TEST,
/*Locn26 35 */  ST_SLEEP,ST_IDLE ,ST_MANMN, ST_PREMN, ST_PRGMN, ST_PLAY, ST_ABORT,ST_TEST,
/*Locn32 36 */  ST_SLEEP,ST_IDLE ,ST_MANMN, ST_PREMN, ST_PRGMN, ST_PLAY, ST_ABORT,ST_TEST,
/*Locn01 37 */  ST_SLEEP,ST_IDLE ,ST_MANMN, ST_PREMN, ST_PRGMN, ST_PLAY, ST_ABORT,ST_TEST,
/*Locn13 38 */  ST_SLEEP,ST_IDLE ,ST_MANMN, ST_PREMN, ST_PRGMN, ST_PLAY, ST_ABORT,ST_TEST,
/*Locn07 39 */  ST_SLEEP,ST_IDLE ,ST_MANMN, ST_PREMN, ST_PRGMN, ST_PLAY, ST_ABORT,ST_TEST,
/*Locn19 40 */  ST_SLEEP,ST_IDLE ,ST_MANMN, ST_PREMN, ST_PRGMN, ST_PLAY, ST_ABORT,ST_TEST,
/*Locn25 41 */  ST_SLEEP,ST_IDLE ,ST_MANMN, ST_PREMN, ST_PRGMN, ST_PLAY, ST_ABORT,ST_TEST,
/*Locn31 42 */  ST_SLEEP,ST_IDLE ,ST_MANMN, ST_PREMN, ST_PRGMN, ST_PLAY, ST_ABORT,ST_TEST,
/* -		 43 */  ST_SLEEP,ST_IDLE, ST_MANMN, ST_PREMN, ST_PRGMN, ST_PLAY, ST_ABORT,ST_TEST,
/*			 44 */  ST_SLEEP,ST_IDLE ,ST_MANMN, ST_PREMN, ST_PRGMN, ST_PLAY, ST_ABORT,ST_TEST,
/*MenuUp 45 */  ST_SLEEP,ST_IDLE, ST_MANMN, ST_PREMN, ST_PRGMN, ST_PLAY, ST_ABORT,ST_TEST,
/*TEST   46 */  ST_SLEEP,ST_TEST, ST_TEST, 	ST_TEST,  ST_TEST,  ST_PLAY, ST_ABORT,ST_TEST,
/*Remote 47 */  ST_SLEEP,ST_IDLE ,ST_MANMN, ST_PREMN, ST_PRGMN, ST_PLAY, ST_ABORT,ST_TEST,
};
// ELO4CHG #2 (end)

// v1.186 start

// C18 to XC8 Compiler Changes
//const rom uchar xtbl_EL05LE2[384] = {
const uchar xtbl_EL05LE2[384] = {
// C18 to XC8 Compiler Changes
//       		Sleep    Idle     ManMain   PreMain   PrgMain   Play	 Abort		Test
/*NoChg	  0 */  ST_SLEEP,ST_IDLE, ST_MANMN, ST_PREMN, ST_PRGMN, ST_PLAY, ST_IDLE,	ST_TEST,
/*MenuDN  1 */  ST_SLEEP,ST_IDLE, ST_MANMN, ST_PREMN, ST_PRGMN, ST_PLAY, ST_ABORT,ST_TEST,
/*Preset  2 */  ST_SLEEP,ST_PREMN,ST_ABORT, ST_PREMN, ST_ABORT, ST_ABORT,ST_ABORT,ST_ABORT,
/*Play	  3 */  ST_SLEEP,ST_IDLE, ST_PLAY,	ST_PLAY,  ST_PLAY,	ST_ABORT,ST_PLAY,	ST_TEST,
/* + 	  4 */  ST_SLEEP,ST_IDLE, ST_MANMN, ST_PREMN, ST_PRGMN, ST_PLAY, ST_ABORT,ST_TEST,
/*Program 5 */  ST_SLEEP,ST_PRGMN,ST_ABORT, ST_ABORT, ST_PRGMN, ST_ABORT,ST_ABORT,ST_ABORT,
/*Manual  6 */  ST_SLEEP,ST_MANMN,ST_MANMN, ST_ABORT, ST_ABORT, ST_ABORT,ST_ABORT,ST_ABORT,
/*Locn06  7 */	ST_SLEEP,ST_IDLE, ST_MANMN, ST_PREMN, ST_PRGMN, ST_PLAY, ST_ABORT,ST_TEST,
/*Locn18  8 */	ST_SLEEP,ST_IDLE, ST_MANMN, ST_PREMN, ST_PRGMN, ST_PLAY, ST_ABORT,ST_TEST,
/*Locn12  9 */	ST_SLEEP,ST_IDLE ,ST_MANMN, ST_PREMN, ST_PRGMN, ST_PLAY, ST_ABORT,ST_TEST,
/*Locn24 10 */  ST_SLEEP,ST_IDLE ,ST_MANMN, ST_PREMN, ST_PRGMN, ST_PLAY, ST_ABORT,ST_TEST,
/*Locn30 11 */  ST_SLEEP,ST_IDLE ,ST_MANMN, ST_PREMN, ST_PRGMN, ST_PLAY, ST_ABORT,ST_TEST,
///*Locn36 12 */ST_SLEEP,ST_IDLE ,ST_MANMN, ST_PREMN, ST_PRGMN, ST_PLAY, ST_ABORT,ST_TEST,
/*Preset  2 */  ST_SLEEP,ST_PREMN,ST_ABORT, ST_PREMN, ST_ABORT, ST_ABORT,ST_ABORT,ST_ABORT,
/*Locn05 13 */  ST_SLEEP,ST_IDLE ,ST_MANMN, ST_PREMN, ST_PRGMN, ST_PLAY, ST_ABORT,ST_TEST,
/*Locn17 14 */  ST_SLEEP,ST_IDLE ,ST_MANMN, ST_PREMN, ST_PRGMN, ST_PLAY, ST_ABORT,ST_TEST,
/*Locn11 15 */  ST_SLEEP,ST_IDLE ,ST_MANMN, ST_PREMN, ST_PRGMN, ST_PLAY, ST_ABORT,ST_TEST,
/*Locn23 16 */  ST_SLEEP,ST_IDLE ,ST_MANMN, ST_PREMN, ST_PRGMN, ST_PLAY, ST_ABORT,ST_TEST,
/*Locn29 17 */  ST_SLEEP,ST_IDLE ,ST_MANMN, ST_PREMN, ST_PRGMN, ST_PLAY, ST_ABORT,ST_TEST,
///*Locn35 18 */ST_SLEEP,ST_IDLE ,ST_MANMN, ST_PREMN, ST_PRGMN, ST_PLAY, ST_ABORT,ST_TEST,
/*Preset  2 */  ST_SLEEP,ST_PREMN,ST_ABORT, ST_PREMN, ST_ABORT, ST_ABORT,ST_ABORT,ST_ABORT,
/*Locn04 19 */	ST_SLEEP,ST_IDLE ,ST_MANMN, ST_PREMN, ST_PRGMN, ST_PLAY, ST_ABORT,ST_TEST,
/*Locn16 20 */	ST_SLEEP,ST_IDLE ,ST_MANMN, ST_PREMN, ST_PRGMN, ST_PLAY, ST_ABORT,ST_TEST,
/*Locn10 21 */	ST_SLEEP,ST_IDLE ,ST_MANMN, ST_PREMN, ST_PRGMN, ST_PLAY, ST_ABORT,ST_TEST,
/*Locn22 22 */  ST_SLEEP,ST_IDLE ,ST_MANMN, ST_PREMN, ST_PRGMN, ST_PLAY, ST_ABORT,ST_TEST,
/*Locn28 23 */  ST_SLEEP,ST_IDLE ,ST_MANMN, ST_PREMN, ST_PRGMN, ST_PLAY, ST_ABORT,ST_TEST,
///*Locn34 24 */ST_SLEEP,ST_IDLE ,ST_MANMN, ST_PREMN, ST_PRGMN, ST_PLAY, ST_ABORT,ST_TEST,
/*Preset  2 */  ST_SLEEP,ST_PREMN,ST_ABORT, ST_PREMN, ST_ABORT, ST_ABORT,ST_ABORT,ST_ABORT,
/*Locn03 25 */  ST_SLEEP,ST_IDLE ,ST_MANMN, ST_PREMN, ST_PRGMN, ST_PLAY, ST_ABORT,ST_TEST,
/*Locn15 26 */  ST_SLEEP,ST_IDLE ,ST_MANMN, ST_PREMN, ST_PRGMN, ST_PLAY, ST_ABORT,ST_TEST,
/*Locn09 27 */  ST_SLEEP,ST_IDLE ,ST_MANMN, ST_PREMN, ST_PRGMN, ST_PLAY, ST_ABORT,ST_TEST,
/*Locn21 28 */  ST_SLEEP,ST_IDLE ,ST_MANMN, ST_PREMN, ST_PRGMN, ST_PLAY, ST_ABORT,ST_TEST,
/*Locn27 29 */  ST_SLEEP,ST_IDLE ,ST_MANMN, ST_PREMN, ST_PRGMN, ST_PLAY, ST_ABORT,ST_TEST,
///*Locn33 30 */ST_SLEEP,ST_IDLE ,ST_MANMN, ST_PREMN, ST_PRGMN, ST_PLAY, ST_ABORT,ST_TEST,
/*Preset  2 */  ST_SLEEP,ST_PREMN,ST_ABORT, ST_PREMN, ST_ABORT, ST_ABORT,ST_ABORT,ST_ABORT,
/*Locn02 31 */	ST_SLEEP,ST_IDLE ,ST_MANMN, ST_PREMN, ST_PRGMN, ST_PLAY, ST_ABORT,ST_TEST,
/*Locn14 32 */	ST_SLEEP,ST_IDLE ,ST_MANMN, ST_PREMN, ST_PRGMN, ST_PLAY, ST_ABORT,ST_TEST,
/*Locn08 33 */	ST_SLEEP,ST_IDLE ,ST_MANMN, ST_PREMN, ST_PRGMN, ST_PLAY, ST_ABORT,ST_TEST,
/*Locn20 34 */  ST_SLEEP,ST_IDLE ,ST_MANMN, ST_PREMN, ST_PRGMN, ST_PLAY, ST_ABORT,ST_TEST,
/*Locn26 35 */  ST_SLEEP,ST_IDLE ,ST_MANMN, ST_PREMN, ST_PRGMN, ST_PLAY, ST_ABORT,ST_TEST,
///*Locn32 36 */ST_SLEEP,ST_IDLE ,ST_MANMN, ST_PREMN, ST_PRGMN, ST_PLAY, ST_ABORT,ST_TEST,
/*Preset  2 */  ST_SLEEP,ST_PREMN,ST_ABORT, ST_PREMN, ST_ABORT, ST_ABORT,ST_ABORT,ST_ABORT,
/*Locn01 37 */  ST_SLEEP,ST_IDLE ,ST_MANMN, ST_PREMN, ST_PRGMN, ST_PLAY, ST_ABORT,ST_TEST,
/*Locn13 38 */  ST_SLEEP,ST_IDLE ,ST_MANMN, ST_PREMN, ST_PRGMN, ST_PLAY, ST_ABORT,ST_TEST,
/*Locn07 39 */  ST_SLEEP,ST_IDLE ,ST_MANMN, ST_PREMN, ST_PRGMN, ST_PLAY, ST_ABORT,ST_TEST,
/*Locn19 40 */  ST_SLEEP,ST_IDLE ,ST_MANMN, ST_PREMN, ST_PRGMN, ST_PLAY, ST_ABORT,ST_TEST,
/*Locn25 41 */  ST_SLEEP,ST_IDLE ,ST_MANMN, ST_PREMN, ST_PRGMN, ST_PLAY, ST_ABORT,ST_TEST,
/*Locn31 42 */  ST_SLEEP,ST_IDLE ,ST_MANMN, ST_PREMN, ST_PRGMN, ST_PLAY, ST_ABORT,ST_TEST,
/* -	 43 */  ST_SLEEP,ST_IDLE, ST_MANMN, ST_PREMN, ST_PRGMN, ST_PLAY, ST_ABORT,ST_TEST,
/*		 44 */  ST_SLEEP,ST_IDLE ,ST_MANMN, ST_PREMN, ST_PRGMN, ST_PLAY, ST_ABORT,ST_TEST,
/*MenuUp 45 */  ST_SLEEP,ST_IDLE, ST_MANMN, ST_PREMN, ST_PRGMN, ST_PLAY, ST_ABORT,ST_TEST,
/*TEST   46 */  ST_SLEEP,ST_TEST, ST_TEST, 	ST_TEST,  ST_TEST,  ST_PLAY, ST_ABORT,ST_TEST,
/*Remote 47 */  ST_SLEEP,ST_IDLE ,ST_MANMN, ST_PREMN, ST_PRGMN, ST_PLAY, ST_ABORT,ST_TEST,
};
// v1.186 end

// C18 to XC8 Compiler Changes
//extern const rom ulong (*lobfuncs[ST_MAX])(int cmd);
extern char (*lobfuncs[ST_MAX])(int cmd);
// C18 to XC8 Compiler Changes

uchar cur_st;//  = ST_IDLE;
uchar prev_st;// = -1;

// Lobster GUI State Machine
//

// C18 to XC8 Compiler Changes
//const rom struct state_mach lobmach = {
const struct state_mach lobmach = {
// C18 to XC8 Compiler Changes

  &cur_st,
  &prev_st,
  &xtbl[0],
  ST_MAX,
//  LOBNUMBUT+1,
//  lobfuncs,
};

//const rom struct state_mach_EL04 lobmach_EL04 = {

// C18 to XC8 Compiler Changes
//const rom struct state_mach lobmach_EL04 = {
const struct state_mach lobmach_EL04 = {
// C18 to XC8 Compiler Changes

  &cur_st,
  &prev_st,
  &xtbl_EL04[0],
  ST_MAX,
//  LOBNUMBUT+1,
//  lobfuncs,
};

// C18 to XC8 Compiler Changes
//const rom struct state_mach lobmach_EL05LE2 = {
const struct state_mach lobmach_EL05LE2 = {
// C18 to XC8 Compiler Changes

  &cur_st,
  &prev_st,
  &xtbl_EL05LE2[0],
  ST_MAX,
//  LOBNUMBUT+1,
//  lobfuncs,
};

